### ISSUE TITLE
Promiscuous Versions

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-meta#623]
This is a meta issue to track mods which have versions that are compatible with far future versions of KSP. Steps are:

1. Find all of them.
2. Determine why they're available.
3. Determine if they should be fixed or not.
4. Fix all those that need to be fixed.

##### 1. No `ksp_version`, `ksp_version_min`, nor `ksp_version_max`
- [x] `ActiveTextureManagement-x86-* (5-0)`
- [x] `BananaForScale-*`
- [x] ~~`CrewManifest (0.5.10-26)`~~ #638 #640
- [x] `EntchenFlag (1.0)`
- [x] `FusTek-SharedAssets (1.0)`
- [x] ~~`KerbalAlarmClock (v3.2.3.0)`~~ #641
- [x] `ModuleAnimateEmissive (v1.4)`
- [x] `NavHud (1.2.1)`
- [x] `OkramSA (1.0)`
- [x] `SDHI-SharedAssets (1.0)`
- [x] ~~`SmartStage (v2.3.1)`~~ #642
- [x] `SolverEngines (v1.4)`
- [x] ~~`ThermalMonitor (1.0)`~~ #643
- [x] `TransferWindowPlanner (v1.3.0.1)`
- [x] `VNG-*`

##### 2. `ksp_version_min` without a `ksp_version_max`
- [x] `AIESAerospace-Unofficial (1.5.1)`
- [x] `AMEG (1.1)` 
- [x] `AnimatedDecouplers-x86 (1.1.4)`
- [x] `AstronomersPack-* (Interstellar.V2)`
- [x] ~~`ColorCodedCans (0.9)`~~ #636 
- [x] `CustomAsteroids-* (v1.1.0)`
- [x] ~~`DockingPortAlignmentIndicator (4.0)`~~ #636
- [x] ~~`EditorExtensions (2.2)`~~ #624 
- [x] `EnvironmentalVisualEnhancements-* (7-4)`
- [x] ~~`HyperEdit (1.4)`~~ #644
- [x] ~~`ImprovedChaseCamera (1.4.0)`~~ #636
- [x] `JSIPartUtilities (v0.3)` #636
- [x] `KDEX (v1.04)`
- [x] `KerbalFoundries (Beta_1.8g)` #636
- [x] ~~`LargeStructuralComponents (10)`~~ #636
- [x] `LSPFlags (v1.9)`
- [x] `ModularRocketSystem (1.7.2)`
- [x] `NavBallTextureExport (1.3)`
- [x] ~~`Proton-Bobcat (1.0)`~~ #636 KSP-CKAN/NetKAN#1705
- [x] ~~`PunishTheLazy (0.01)`~~ #636
- [x] `RasterPropMonitor-Core (v0.19.1)`
- [x] `ReflectionPlugin (1.2)`
- [x] ~~`RocketdyneF-1 (1.2)`~~ #636
- [x] ~~`SovietEngines (1.1)`~~ #636 KSP-CKAN/NetKAN#1705
- [x] ~~`SpaceFacotry-Vostok-unofficial (1.0)`~~ #636
- [x] ~~`SpaceFactory-Voskhod-unofficial (2.0)`~~ #636
- [x] `SpaceY-Lifters (0.17.2)`
- [x] ~~`StripSymmetry (v1.6)`~~ #636 KSP-CKAN/NetKAN#1705
- [x] `surfacelights (1.0)`
- [x] `Tantares (29)` #645
- [x] `TantaresLV (12.1)`
- [x] `TCShipInfo (0.3)`
- [x] `xScience (4.6)`

##### 3. `ksp_version` of `any`
- [x] `DogeCoinFlag (v1.02)`
- [ ] `KSP-AVC (1.1.5.0)`
- [x] `LandingHeight (1.4)`
- [ ] `MiniAVC (1.0.3.0)`
- [x] `PartMapper (0.3.0)`
- [x] ~~`RCSLandAid (2.1)`~~ #646
- [x] `Sarkomand (v1.0)`

##### 4. `ksp_version` of `1.0` but newer version is more restrictive
- [x] ~~`BULB (1.1)`~~ #627
- [x] ~~`CraftHistory (1.4)`~~ #627
- [x] ~~`HotRockets (1.0)`~~ #627
- [x] ~~`KerbalScienceExchange (1.1)`~~ #627
- [x] ~~`PlanetShine (0.2.2.3)`~~ #625
- [x] ~~`RecoverAll (1.2)`~~ #627
- [x] ~~`ScienceFunding (1.1)`~~ #627
- [x] ~~`TacFuelBalancer (v2.5)`~~ #627
- [x] ~~`TweakableEverything (1.9.1)`~~ #627 #633

##### Both Reasons 2 **and** 3 
- [x] `kribubble (1.1)`
- [x] `krispeeder1 (1.0)`
- [x] `MOVAP (1.0)`

**Comment by SkyMarshal** [comment]
I'd argue a `ksp_version` of 1.0 to also be promiscuous, especially if more recent versions of the mod have more specific versions.  An example is `PlanetShine 0.2.2.2` which is currently displayed as compatible with KSP 1.0.4 when actual most recent version is `PlanetShine 0.2.3.1` which is only compatible with KSP 1.0.2.

**Comment by SkyMarshal** [comment]
PlanetShine 0.2.2.3 is also erroneously indicating it is compatible with 1.0.4.

**Comment by dbent** [comment]
@SkyMarshal I have those listed under reason 4.

**Comment by SkyMarshal** [comment]
Fantastic.  I'd help more but I've commitments tonight.

**Comment by SkyMarshal** [comment]
Literally every version of AnimatedDecouplers since v1.0.1 has had the `ksp_version_min` tag set to `1.0` with no max tag.  No idea what to do about those.  Also: Some of the others in reason two have ONLY one version indexed.  No idea what should be done there.

**Comment by SkyMarshal** [comment]
FFFFF- Why are there so many mods from kerbalstuff with crapped up versions?

**Comment by SkyMarshal** [comment]
[x] Science! is a good example.  The KSP-AVC file has only a  "KSP_VERSION" line and that somehow became `ksp_version_min`

**Comment by dbent** [comment]
Alright, I think every instance of there being an old promiscuous version when a non-promiscuous newer version exists has been fixed.

Next I'll look for versions where the mod author has actually specified version restrictions that we're not reflecting.

**Comment by plague006** [comment]
Are we assuming flags will stay safe in perpetuity? Even if the methods for mod flags change (which they shouldn't), it's just an image file being installed and shouldn't have any negative effect.

**Comment by pjf** [comment]
@plague006 : I think we're pretty safe that flags will remain platform independent. If flags somehow change radically in the future we can re-address then.

**Comment by Gustavo6046** [comment]
AIESAerospace-Unofficial confirmed for 1.0.0.

**Comment by politas** [comment]
You missed RealPlume in "4. ksp_version of 1.0 but newer version is more restrictive"
#881

**Comment by politas** [comment]
You also missed RemoteTech-Config-RSS in KSP_Min with no KSP-Max -  #906 sorts it out, since RSS now handles it with a ModManager file (much better).

**Comment by plague006** [comment]
The only 2 outstanding mods are ksp-avc and mini-avc and if there's an issue with those we'll get 1,000 reports per minute anyway.

Calling this complete.
